package com.arabie.dao4;// default package
// Generated Mar 21, 2021, 2:20:28 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
//@Entity
//@Table(name = "teacher")
//@DiscriminatorValue("teacher")
//@PrimaryKeyJoinColumn(name = "id")
public class Teacher  extends Person implements java.io.Serializable {


//     private Integer id;
//    @Column(name = "hire_date")
     private Date hireDate;

    public Teacher() {
    }

    public Teacher(String firstName, String lastName, Date hireDate) {
       super.setFirstName(firstName);
       super.setLastName(lastName);
       this.hireDate = hireDate;
    }
//
//    public Integer getId() {
//        return this.id;
//    }
//
//    public void setId(Integer id) {
//        this.id = id;
//    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "hireDate=" + hireDate +
                "} " + super.toString();
    }
}


